---
title: 
tags:
  - java
  - programming
  - spring
  - exception
  - translator
  - database
publish: true
date: 2024-12-14 00:01
---

## 체크 예외와 인터페이스

서비스 계층은 가급적 특정 구현 기술에 의존하지 않고, 순수하게 유지하는 것이 좋다. 이렇게 하려면 예외에 대한 의존도 함께 해결해야 한다.

예를 들어서 서비스가 처리할 수 없는 `SQLException`에 대한 의존을 제거하려면 어떻게 해야할까?

서비스가 처리할 수 없으므로 리포지토리가 던지는 `SQLException` 체크 예외를 런타임 예외로 전환해서 서비스 계층에 던지면 서비스 계층이 해당 예외를 무시할 수 있기 때문에, 특정 구현 기술에 의존하는 부분을 제거하고 서비스 계층을 순수하게 유지할 수 있다.

### 인터페이스 도입

먼저 `MemberRepository` 인터페이스도 도입해서 구현 기술을 쉽게 변경할 수 있도록 변경한다.

```java
public interface MemberRepository {
	Member save(Member member);
	Member findById(String memberId);
	void update(String memberId, int money);
	void delete(String memberId);
}
```

그런데 앞서서 예제를 시작할 때부터 왜 이런 인터페이스를 만들지 않았을까? 바로 `SQLException`이 체크 예외이기 때문이다.

체크 예외를 사용하려면 인터페이스에도 해당 체크 예외가 선언되어 있어야 한다. 예를 들면 다음과 같은 코드가 된다.

```java
public interface MemberRepositoryEx {
	Member save(Member member) throws SQLException;
	Member findById(String memberId) throws SQLException;
	void update(String memberId, int money) throws SQLException;
	void delete(String memberId) throws SQLException;
}
```

그런데 인터페이스가 이렇게 구현되면, 이미 인터페이스 자체가 순수하지 않고 `java.sql.SQLException` 이라는 특정 기술에 의존하게 된다.

#### 체크 예외 코드에 인터페이스 도입시 문제점 - 구현 클래스

```java
@Slf4j
public class MemberRepositoryV3 implements MemberRepositoryEx {
	public Member save(Member member) throws SQLException {
		String sql = "insert into member(member_id, money) values(?, ?)";
	}
}
```

인터페이스의 구현체가 체크 예외를 던지려면, 인터페이스 메서드에 먼저 체크 예외를 던지는 부분이 선언되어 있어야 한다. 그래야 구현 클래스의 메서드도 체크 예외를 던질 수 있다.

참고로 구현 클래스의 메서드에 선언할 수 있는 예외는 부모 타입에서 던진 예외와 같거나 하위 타입이어야 한다.

#### 특정 기술에 종속되는 인터페이스

구현 기술을 쉽게 변경하기 위해서 (OCP와 DI를 활용하기 위해서) 인터페이스를 도입하더라도 `SQLException`과 같은 특정 구현 기술에 종송적인 체크 예외를 사용하게 되면 인터페이스에도 해당 예외를 포함해야 한다.

하지만 이것은 우리가 원하던 순수한 인터페이스가 아니다. `JDBC`에 종속적인 인터페이스일 뿐이다.

인터페이스를 만드는 목적은 구현체를 쉽게 변경하기 위함인데, 이미 인터페이스가 특정 구현 기술에 오염이 되어 버렸다. 향후 `JDBC`가 아닌 다른 기술로 변경한다면 인터페이스 자체를 변경해야 한다.

#### 런타임 예외와 인터페이스

런타임 예외는 이런 부분에서 자유롭다. 인터페이스에 런타임 예외를 따로 선언하지 않아도 된다. 따라서 인터페이스가 특정 기술에 종속적일 필요가 없다.

## 런타임 예외 적용

실제 코드에 런타임 예외를 사용하도록 적용해본다.

먼저 `SQLException` 체크 예외를 런타임 예외로 변경하기 위해 다음과 같이 런타임 예외 클래스를 작성한다.

```java title="MyDbException.java"
public class MyDbException extends RuntimeException {
    public MyDbException() {
    }

    public MyDbException(String message) {
        super(message);
    }

    public MyDbException(String message, Throwable cause) {
        super(message, cause);
    }

    public MyDbException(Throwable cause) {
        super(cause);
    }
}
```

그리고 `MemberRepository` 인터페이스를 작성한다.

```java
public interface MemberRepository {
    Member save(Member member);
    Member findById(String memberId);
    void update(String memberId, int money);
    void delete(String memberId);
}
```

다음으로 `MemberRepository` 인터페이스를 의존하는 `MemberRepositoryV4_1`을 작성한다.

```java title="MemberRepositoryV4_1.java"
/**
 * 예외 누수 문제 해결
 * 체크 예외를 런타임 예외로 변경
* MemberRepository 인터페이스 의존
 * throws SQLException 제거
 */
@Slf4j
@RequiredArgsConstructor
public class MemberRepositoryV4_1 implements MemberRepository {
    private final DataSource dataSource;

    @Override
    public Member save(Member member) {
        String sql = "INSERT INTO member(member_id, money) VALUES(?, ?)";

        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setString(1, member.getMemberId());
            statement.setInt(2, member.getMoney());

            statement.executeUpdate();

            return member;
        } catch (SQLException e) {
            throw new MyDbException(e);
        } finally {
            close(connection, statement, null);
        }
    }

    @Override
    public void delete(String memberId) {
        String sql = "DELETE FROM member WHERE member_id = ?";
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setString(1, memberId);

            int affectedRows = statement.executeUpdate();
            log.info("affectedRows = {}", affectedRows);
        } catch (SQLException e) {
            throw new MyDbException(e);
        } finally {
            close(connection, statement, null);
        }
    }

    @Override
    public void update(String memberId, int money) {
        String sql = "UPDATE member SET money = ? WHERE member_id = ?";
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setInt(1, money);
            statement.setString(2, memberId);

            int affectedRows = statement.executeUpdate();
            log.info("affectedRows = {}", affectedRows);
        } catch (SQLException e) {
            throw new MyDbException(e);
        } finally {
            close(connection, statement, null);
        }
    }

    @Override
    public Member findById(String memberId) {
        String sql = "SELECT * FROM member WHERE member_id = ?";
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setString(1, memberId);
            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                Member member = new Member();
                member.setMemberId(resultSet.getString("member_id"));
                member.setMoney(resultSet.getInt("money"));
                return member;
            } else {
                throw new NoSuchElementException("Member not found memberId = " + memberId);
            }

        } catch (SQLException e) {
            throw new MyDbException(e);
        } finally {
            close(connection, statement, resultSet);
        }
    }

    private void close(Connection connection, Statement statement, ResultSet resultSet) {
        JdbcUtils.closeResultSet(resultSet);
        JdbcUtils.closeStatement(statement);

        // 주의! 트랜잭션 동기화를 사용하려면 DataSourceUtils를 사용해야 한다.
        DataSourceUtils.releaseConnection(connection, dataSource);
    }

    private Connection getConnection() throws SQLException {
        // 주의! 트랜잭션 동기화를 사용하려면 DataSourceUtils를 사용해야 한다.
        Connection connection = DataSourceUtils.getConnection(dataSource);

        log.info("getConnection = {}, class = {}", connection, connection.getClass());

        return connection;
    }
}
```

이 코드의 핵심은 두 가지다.

- `MemberRepository` 인터페이스 의존
- `SQLException`이라는 체크 예외를 `MyDbException`이라는 런타임 예외로 전환해서 던지는 부분

이제 다음과 같이 서비스 코드도 변경한다.

```java title="MemberServiceV4.java"
/**
 * 예외 누수 문제 해결
 * SQLException 제거
 * MemberRepository 인터페이스 의존
 */
@Slf4j
@RequiredArgsConstructor
public class MemberServiceV4 {
    private final MemberRepository memberRepository;

    @Transactional
    public void transfer(String fromId, String toId, int money) {
        Member fromMember = memberRepository.findById(fromId);
        Member toMember = memberRepository.findById(toId);

        memberRepository.update(fromId, fromMember.getMoney() - money);
        validation(toMember);
        memberRepository.update(toId, toMember.getMoney() + money);
    }

    private static void validation(Member toMember) {
        if (toMember.getMemberId().equals("ex")) {
            throw new IllegalStateException("이체 중 예외 발생");
        }
    }
}
```

앞서 리포지토리에서 체크 예외를 런타임 예외로 변환해서 던지기 때문에 서비스 레이어에서는 무시해도 된다. 따라서 현재 서비스 계층은 거의 순수한 비즈니스 로직만 존재하게 된다.

마지막으로 다음과 같이 테스트를 작성한다.

```java
/**
 * 예외 누수 문제 해결
 * SQLException 제거
 * MemberRepository 인터페이스 의존
 */
@SpringBootTest
@Slf4j
class MemberServiceV4Test {
    public static final String MEMBER_A = "memberA";
    public static final String MEMBER_B = "memberB";
    public static final String MEMBER_EX = "ex";

    @Autowired
    private MemberRepository memberRepository;
    @Autowired
    private MemberServiceV4 memberService;

    @TestConfiguration
    static class TestConfig {
        private final DataSource dataSource;

        public TestConfig(DataSource dataSource) {
            this.dataSource = dataSource;
        }

        @Bean
        MemberRepository memberRepositoryV4() {
            return new MemberRepositoryV4_1(dataSource);
        }

        @Bean
        MemberServiceV4 memberServiceV4() {
            return new MemberServiceV4(memberRepositoryV4());
        }
    }


    @Test
    void AopCheck() {
        log.info("memberService class={}", memberService.getClass());
        log.info("memberRepository class={}", memberRepository.getClass());
        Assertions.assertThat(AopUtils.isAopProxy(memberService)).isTrue();
        Assertions.assertThat(AopUtils.isAopProxy(memberRepository)).isFalse();
    }

    @AfterEach
    void afterEach() {
        memberRepository.delete(MEMBER_A);
        memberRepository.delete(MEMBER_B);
        memberRepository.delete(MEMBER_EX);
    }

    @Test
    @DisplayName("정상 이체")
    void transfer() {
        // GIVEN
        Member memberA = new Member(MEMBER_A, 10000);
        Member memberB = new Member(MEMBER_B, 10000);

        memberRepository.save(memberA);
        memberRepository.save(memberB);

        // WHEN
        memberService.transfer(memberA.getMemberId(), memberB.getMemberId(), 2000);

        // THEN
        Member findMemberA = memberRepository.findById(memberA.getMemberId());
        Member findMemberB = memberRepository.findById(memberB.getMemberId());

        Assertions.assertThat(findMemberA.getMoney()).isEqualTo(8000);
        Assertions.assertThat(findMemberB.getMoney()).isEqualTo(12000);
    }

    @Test
    @DisplayName("이체중 예외 발생")
    void transferToEx() {
        // GIVEN
        Member memberA = new Member(MEMBER_A, 10000);
        Member memberEx = new Member(MEMBER_EX, 10000);

        memberRepository.save(memberA);
        memberRepository.save(memberEx);

        // WHEN
        Assertions
                .assertThatThrownBy(
                        () -> memberService.transfer(memberA.getMemberId(), memberEx.getMemberId(), 2000))
                .isInstanceOf(IllegalStateException.class);

        // THEN
        Member findMemberA = memberRepository.findById(memberA.getMemberId());
        Member findMemberB = memberRepository.findById(memberEx.getMemberId());

        Assertions.assertThat(findMemberA.getMoney()).isEqualTo(10000);
        Assertions.assertThat(findMemberB.getMoney()).isEqualTo(10000);
    }
}
```

실행하면 정상적으로 테스트를 패스한다.

> [!summary] 정리
>
> - 체크 예외를 런타임 예외로 변환하면서 인터페이스와 서비스 계층의 순수성을 유지할 수 있게 되었다.
> - 덕분에 향후 `JDBC`에서 다른 구현 기술로 변경하더라도 서비스 계층의 코드를 변경하지 않고 유지할 수 있다.

**남은 문제**

리포지토리에서 넘어오는 특정한 예외의 경우 복구를 시도할 수도 있다.

그런데 지금 방식은 항상 `MyDbException`이라는 예외만 넘어오기 때문에 예외를 구분할 수 없는 단점이 있다. 만약 특정 상황에서 예외를 잡아서 복구하고 싶으면 예외를 어떻게 구분해서 처리해야 할까?

## 데이터 접근 예외 직접 구현

데이터베이스 오류에 따라서 특정 예외는 복구하고 싶을 수 있다. 예를 들어서 회원 가입 시 DB에 이미 같은 ID가 있으면 ID 뒤에 숫자를 붙여서 새로운 ID를 만들어야 한다고 가정해보자.

ID를 `hello`라고 가입 시도 했는데, 이미 같은 아이디가 있으면 `hello12345` 같이 뒤에 임의의 숫자를 붙여서 가입하는 것이다.

데이터를 DB에 저장할 때 같은 ID가 이미 데이터베이스에 저장되어 있다면, 데이터베이스는 오류 코드를 반환하고, 이 오류 코드를 받은 `JDBC` 드라이버는 `SQLException`을 던진다. 그리고 `SQLException`에는 데이터베이스가 제공하는 `errorCode`라는 것이 들어있다.

![[database-exception-1.png]]

1. 클라이언트가 `SQL`을 전달하고 실행 했을 때 데이터베이스에 오류가 발생하면 해당 오류에 관한 코드를 포함하여 다시 `JDBC` 드라이버에 전달한다.
2. `JDBC` 드라이버는 해당 에러를 바탕으로 `SQLException`을 던지고 리포지토리는 해당 예외의 예외 코드를 바탕으로 `MyDuplicateKeyException` 예외를 던진다.

**H2 데이터베이스의 키 중복 오류 코드**

```java
e.getErrorCode() == 23505
```

`SQLException` 내부에 들어있는 이 `errorCode`를 활용하면 데이터베이스에서 어떤 문제가 발생했는지 확인할 수 있다.

- `23505`: 키 중복 오류
- `42000`: SQL 문법 오류

참고로 같은 오류여도 각각의 데이터베이스마다 정의된 오류 코드가 다르다. 따라서 오류 코드를 사용할 때는 데이터베이스 메뉴얼을 확인해야 한다.

- H2 키 중복 오류 코드: `23505`
- MySQL 키 중복 오류 코드: `1062`

> [H2 데이터베이스 오류 코드 메뉴얼](https://www.h2database.com/javadoc/org/h2/api/ErrorCode.html)

서비스 계층에서는 예외 복구를 위해 키 중복 오류를 확인할 수 있어야 한다. 그래야 새로운 ID를 만들어서 다시 저장을 시도할 수 있기 때문이다. 이러한 과정이 바로 예외를 확인해서 복구하는 과정이다.

리포지토리는 `SQLException`을 서비스 계층에 던지고, 서비스 계층은 이 예외의 오류 코드를 확인해서 키 중복 오류인 경우 새로운 ID를 만들어서 다시 저장하면 된다.

> [!error] 서비스 계층 오염 문제가 재발생
> 그런데 SQLException에 들어있는 오류 코드를 활용하기 위해서 SQLException을 서비스 계층으로 던지게 되면 서비스 계층이 SQLException이라는 JDBC 기술에 의존하게 되면서 지금까지 우리가 개선했던 서비스 계층의 순수성이 무너진다.

이 문제를 해결하려면 앞서 학습한 것 처럼 리포지토리에서 예외를 변환해서 던지면 된다.

- `SQLException -> MyDuplicateKeyException`

다음과 같이 예외를 구현해보자.

```java title="MyDuplicateKeyException.java"
public class MyDuplicateKeyException extends MyDbException {
    public MyDuplicateKeyException() {
    }

    public MyDuplicateKeyException(String message) {
        super(message);
    }

    public MyDuplicateKeyException(String message, Throwable cause) {
        super(message, cause);
    }

    public MyDuplicateKeyException(Throwable cause) {
        super(cause);
    }
}
```

- 기존에 사용했던 `MyDbException`을 상속받아서 의미있는 계층을 형성한다. 이렇게하면 데이터베이스 관련 예외라는 계층을 만들 수 있다.
- 그리고 이름도 `MyDuplicateKeyException`이라는 이름을 지었다. 이 예외는 데이터 중복의 경우에만 던져야 한다.
- 이 예외는 우리가 직접 만든 것이기 때문에, `JDBC`나 `JPA` 같은 특정 기술에 종속적이지 않다. 따라서 이 예외를 사용하더라도 서비스 계층의 순수성을 유지할 수 있다.

이제 `MyDuplicateKeyException`를 이용해보기 위해서 다음과 같은 테스트 코드를 만든다.

```java title="ExTrnslatorV1Test.java"
@Slf4j
public class ExTranslatorV1Test {
    Repository repository;
    Service service;

    @BeforeEach
    void beforeEach() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(URL, USERNAME, PASSWORD);
        repository = new Repository(dataSource);
        service = new Service(repository);
    }

    @Test
    void duplicateKeySave() {
        service.create("myId");
        service.create("myId");

    }

    @Slf4j
    @RequiredArgsConstructor    static class Service {
        private final Repository repository;

        void create(String memberId) {
            Member member = new Member(memberId, 0);

            try {
                Member saved = repository.save(member);
                log.info("saveId = {}", saved.getMemberId());
            } catch (MyDuplicateKeyException e) {
                log.info("키 중복, 복구 시도");
                String retryId = generateNewId(memberId);
                log.info("retryId = {}", retryId);
                repository.save(new Member(retryId, 0));
            } catch (MyDbException e) {
                log.info("데이터 접근 계층 예외", e);
                throw e;
            }
        }

        private String generateNewId(String memberId) {
            return memberId + new Random().nextInt(10000);
        }
    }


    @RequiredArgsConstructor
    static class Repository {
        private final DataSource dataSource;

        public Member save(Member member) {
            String sql = "INSERT INTO member(member_id, money) VALUES(?, ?)";
            Connection con = null;
            PreparedStatement preparedStatement = null;

            try {
                con = dataSource.getConnection();
                preparedStatement = con.prepareStatement(sql);
                preparedStatement.setString(1, member.getMemberId());
                preparedStatement.setInt(2, member.getMoney());
                preparedStatement.executeUpdate();

                return member;
            } catch (SQLException e) {
                if (e.getErrorCode() == 23505) {
                    throw new MyDuplicateKeyException(e);
                }

                throw new MyDbException(e);
            } finally {
                JdbcUtils.closeStatement(preparedStatement);
                JdbcUtils.closeConnection(con);
            }
        }
    }
}
```

`Repository`를 먼저 살펴보면, `e.getErrorCode() == 23505`인 경우 `MyDuplicateKeyException`을 던지고 그 외엔 모두 `MyDbException`을 던진다.

`Service`를 살펴보면 처음에 멤버를 저장하려고 시도한다. 만약 기존에 `ID`가 동일한 멤버가 있으면 `generateNewId()`를 통해서 새로운 멤버 아이디를 생성하고, 다시 저장한다.

만약 복구할 수 없는 예외(`MyDbException`)인 경우 로그만 남기고 다시 예외를 던진다. 참고로 이렇게 복구할 수 없는 예외의 경우 공통으로 예외를 처리하는 곳에서 예외 로그를 남기는 것이 좋다.

> [!summary] 정리
>
> - `SQL ErrorCode`로 데이터베이스에 어떤 오류가 있는지 확인할 수 있었다.
> - 예외 변환을 통해 `SQLException`을 특정 기술에 의존하지 않는 직접 만든 예외인 `MyDuplicateKeyException`으로 변환할 수 있었다.
> - 리포지토리 계층이 예외를 변환해준 덕분에 서비스 계층은 특정 기술에 의존하지 않는 `MyDuplicateKeyException`을 사용해서 문제를 복구하고, 서비스 계층의 순수성도 유지할 수 있었다.

**남은 문제**

`SQL ErrorCode`는 각각의 데이터베이스 마다 다르다. 결과적으로 데이터베이스가 변경되면 `ErrorCode`도 모두 변경해야 한다.

데이터베이스가 전달하는 오류는 키 중복 뿐만 아니라 락이 걸린 경우, SQL 문법에 오류가 있는 경우 등 수십, 수백가지 오류 코드가 존재한다. 이 모든 상황에 맞는 예외를 지금처럼 다 만들어야 할까? 추가로 앞서 이야기한 것 처럼 데이터베이스마다 이 오류 코드는 모두 다르다.

> 공통적인 용도지만 세부적인 구현이 존재한다. 따라서 추상화가 필요하다.

## 스프링 예외 추상화 이해

스프링은 앞서 설명한 문제들을 해결하기 위해 데이터 접근과 관련된 예외를 추상화해서 제공한다. 다음의 그림을 참고하자.

![[spring-data-access-exception-layer-1.png]]

- 스프링은 데이터 접근 계층에 대한 수십 가지 예외를 정리해서 일관된 예외 계층을 제공한다.
- 각각의 예외는 특정 기술에 종속적이지 않게 설계되어 있다. 따라서 서비스 계층에서도 스프링이 제공하는 예외를 사용하면 된다. 예를 들어서 `JDBC`를 사용하든 `JPA`를 사용하든 스프링이 제공하는 예외를 사용하면 된다.
- `JDBC`나 `JPA`를 사용할 때 발생하는 예외를 스프링이 제공하는 예외로 변환해주는 역할도 스프링이 제공한다.
- 참고로 그림을 단순화 하기 위해 일부 계층을 생략했다.

> 예외의 최고 상위는 `org.springframework.dao.DataAcessException`이다. 그림에서 보는 것 처럼 런타임 예외를 상속 받았기 때문에 스프링이 제공하는 데이터 접근 계층의 모든 예외는 런타임 예외이다.

#### DataAccessException

그림을 참고하면 `DataAccessException`은 크게 두 가지로 구분하는데 `NonTransient` 예외와 `Transient` 예외이다.

**Transient**

`Transient`는 일시적이라는 뜻이다. `Transient` 하위 예외는 동일한 `SQL`을 다시 시도했을 때 성공할 가능성이 있다.

예를 들어서 쿼리 타임아웃, 락과 관련된 오류들이다. 이런 오류들은 데이터베이스 상태가 좋아지거나 락이 풀렸을 때 다시 시도하면 성공할 수도 있다.

**NonTransient**

`NonTransient`는 일시적이지 않다는 뜻이다. 같은 `SQL`을 그대로 반복해서 실행하면 실패한다.

SQL 문법 오류, 데이터베이스 제약조건 위배 등이 있다.

> 참고: 스프링 메뉴얼에 모든 예외가 정리되어 있지는 않기 때문에 코드를 직접 열어서 확인해보는 것이 필요하다.

## 스프링이 제공하는 예외 변환기

개발자가 직접 데이터베이스의 에러코드를 기반으로 수십, 수백가지의 예외를 정의하고 해당 예외를 사용해서 어떤 로직을 수행한다는 것은 너무 현실성이 없다.

스프링은 데이터베이스에서 발생하는 오류 코드를 스프링이 정의한 예외로 자동으로 변환해주는 **변환기**를 제공한다.

코드를 통해 스프링이 제공하는 예외 변환기를 테스트 코드를 통해 알아본다.

```java
@Slf4j
public class SpringExceptionTranslatorTest {
    DataSource dataSource;

    @BeforeEach
    void beforeEach() {
        dataSource = new DriverManagerDataSource(URL, USERNAME, PASSWORD);
    }

    @Test
    void exceptionTranslator() {
        String sql = "select bad grammar";

        try {
            Connection con = dataSource.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.executeQuery();
        } catch (SQLException e) {
            assertThat(e.getErrorCode()).isEqualTo(42122);

            //org.springframework.jdbc.support.sql-error-codes.xml
            SQLExceptionTranslator exTranslator = new
                    SQLErrorCodeSQLExceptionTranslator(dataSource);

            //org.springframework.jdbc.BadSqlGrammarException
            DataAccessException resultEx = exTranslator.translate("select", sql,
                    e);
            log.info("resultEx", resultEx);

            assertThat(resultEx.getClass()).isEqualTo(BadSqlGrammarException.class);
        }
    }
}
```

스프링이 제공하는 SQL 예외 변환기는 다음과 같이 사용하면 된다.

```java
SQLExceptionTranslator exTranslator = new SQLErrorCodeSQLExceptionTranslator(dataSource);

DataAccessException resultEx = exTranslator.translate("select", sql, e);
```

- `translate()` 메서드의 첫 번째 파라미터는 읽을 수 있는 설명이고, 두 번째는 실행한 `sql`, 마지막은 발생된 `SQLException`을 전달하면 된다. 이렇게하면 적절한 스프링 데이터 접근 계층의 예외로 변환해서 반환해준다.
- 예제에서는 SQL 문법이 잘못되었으므로 `BadqlGrammarException`을 반환하는 것을 확인할 수 있다.
  - 눈에 보이는 반환 타입은 최상위 타입인 `DataAccessException`이지만 `assertThat()`을 확인하면 된다. 실제로는 `BadSqlGrammarException` 예외가 반환된다.
  - 참고로 `BadSqlGrammarException`은 최상위 타입인 `DataAccessException`을 상속 받아서 만들어진다.

각각의 DB마다 `SQL ErrorCode`는 다르다. 그런데 스프링은 어떻게 각각의 DB가 제공하는 `SQL ErrorCode`까지 고려해서 예외를 변환할 수 있을까?

비밀은 바로 다음 파일에 있다.

```xml title="sql-error-codes.xml"
<bean id="H2" class="org.springframework.jdbc.support.SQLErrorCodes">
    <property name="badSqlGrammarCodes">
       <value>42000,42001,42101,42102,42111,42112,42121,42122,42132</value>
    </property>    <property name="duplicateKeyCodes">
       <value>23001,23505</value>
    </property>    <property name="dataIntegrityViolationCodes">
       <value>22001,22003,22012,22018,22025,23000,23002,23003,23502,23503,23506,23507,23513</value>
    </property>    <property name="dataAccessResourceFailureCodes">
       <value>90046,90100,90117,90121,90126</value>
    </property>    <property name="cannotAcquireLockCodes">
       <value>50200</value>
    </property>
</bean>
```

스프링 SQL 예외 변환기는 SQL ErrorCode를 이 파일에 대입해서 어떤 스프링 데이터 접근 예외로 전환해야 할지 찾아낸다. 예를 들어서 `H2` 데이터베이스에서 `42000`이 발생하면 `basSqlGrammarCodes`이기 때문에 `BadSqlGrammarException`을 반환한다.

해당 파일을 확인해보면 10개 이상, 대부분의 관계형 데이터베이스를 지원하는 것을 확인할 수 있다.

> [!summary] 정리
>
> - 스프링은 데이터 접근 계층에 대한 일관된 예외 추상화를 제공한다.
> - 스프링은 SQL 예외 변환기를 통해서 `SQLException`의 `ErrorCode`에 맞는 적절한 스프링 데이터 접근 예외로 변환해준다.
> - 만약 서비스, 컨트롤러 계층에서 예외 처리가 필요하면 특정 기술에 종속적인 `SQLException` 같은 예외를 직접 사용하는 것이 아니라, 스프링이 제공하는 데이터 접근 예외를 사용하면 된다.
> - 스프링 예외 추상화 덕분에 특정 기술에 종속적이지 않게 되었다. 이제 `JDBC`에서 `JPA` 같은 기술로 변경되어도 예외로 인한 변경을 최소화 할 수 있다. 향후 `JDBC`에서 `JPA`로 기술을 변경하더라도 스프링은 `JPA` 예외를 적절한 스프링 데이터 접근 예외로 변환해준다.
> - 물론 스프링이 제공하는 예외를 사용하기 때문에 스프링에 대한 기술 종속성은 발생하겠지만, 스프링에 대한 기술 종속성까지 완전히 제거하려면 예외를 모두 정의하고 예외 반환도 직접 해야한다. 현실적이지 않다.

## 스프링 예외 추상화 적용

이제 앞서 구현한 어플리케이션에 스프링이 제공하는 `데이터 접근 예외 추상화`와 `SQL 예외 변환기`를 적용해본다.

```java title="MemberRepositoryV4_2.java"
@Slf4j
@RequiredArgsConstructor
public class MemberRepositoryV4_2 implements MemberRepository {
    private final DataSource dataSource;
    private final SQLExceptionTranslator translator;

    public MemberRepositoryV4_2(DataSource dataSource) {
        this.dataSource = dataSource;
        this.translator = new SQLErrorCodeSQLExceptionTranslator(dataSource);
    }

    @Override
    public Member save(Member member) {
        String sql = "INSERT INTO member(member_id, money) VALUES(?, ?)";

        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setString(1, member.getMemberId());
            statement.setInt(2, member.getMoney());

            statement.executeUpdate();

            return member;
        } catch (SQLException e) {
            throw translator.translate("save", sql, e);
        } finally {
            close(connection, statement, null);
        }
    }

    @Override
    public void delete(String memberId) {
        String sql = "DELETE FROM member WHERE member_id = ?";
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setString(1, memberId);

            int affectedRows = statement.executeUpdate();
            log.info("affectedRows = {}", affectedRows);
        } catch (SQLException e) {
            throw translator.translate("delete", sql, e);
        } finally {
            close(connection, statement, null);
        }
    }

    @Override
    public void update(String memberId, int money) {
        String sql = "UPDATE member SET money = ? WHERE member_id = ?";
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setInt(1, money);
            statement.setString(2, memberId);

            int affectedRows = statement.executeUpdate();
            log.info("affectedRows = {}", affectedRows);
        } catch (SQLException e) {
            throw translator.translate("update", sql, e);
        } finally {
            close(connection, statement, null);
        }
    }

    @Override
    public Member findById(String memberId) {
        String sql = "SELECT * FROM member WHERE member_id = ?";
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            connection = getConnection();
            statement = connection.prepareStatement(sql);
            statement.setString(1, memberId);
            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                Member member = new Member();
                member.setMemberId(resultSet.getString("member_id"));
                member.setMoney(resultSet.getInt("money"));
                return member;
            } else {
                throw new NoSuchElementException("Member not found memberId = " + memberId);
            }

        } catch (SQLException e) {
            throw translator.translate("findById", sql, e);
        } finally {
            close(connection, statement, resultSet);
        }
    }

    private void close(Connection connection, Statement statement, ResultSet resultSet) {
        JdbcUtils.closeResultSet(resultSet);
        JdbcUtils.closeStatement(statement);

        // 주의! 트랜잭션 동기화를 사용하려면 DataSourceUtils를 사용해야 한다.
        DataSourceUtils.releaseConnection(connection, dataSource);
    }

    private Connection getConnection() throws SQLException {
        // 주의! 트랜잭션 동기화를 사용하려면 DataSourceUtils를 사용해야 한다.
        Connection connection = DataSourceUtils.getConnection(dataSource);

        log.info("getConnection = {}, class = {}", connection, connection.getClass());

        return connection;
    }
}
```

`MemberRepositoryV4_2`는 `final` 키워드 덕에 생성자에서 `SQLExceptionTranslator`의 구현체를 반드시 주입 받아야 한다. 여기서는 직접 생성자를 작성해 주입 했다.

따라서 생성자에서 `new SQLErrorCodeSQLExceptionTranslator(dataSource)`를 통해 구현체를 주입한다.

이 후에 사용할 때는 다음과 같이 사용하면 된다.

```java
@Override
public Member save(Member member) {
    String sql = "INSERT INTO member(member_id, money) VALUES(?, ?)";

    Connection connection = null;
    PreparedStatement statement = null;

    try {
        connection = getConnection();
        statement = connection.prepareStatement(sql);
        statement.setString(1, member.getMemberId());
        statement.setInt(2, member.getMoney());

        statement.executeUpdate();

        return member;
    } catch (SQLException e) {
        throw translator.translate("save", sql, e);
    } finally {
        close(connection, statement, null);
    }
}
```

데이터베이스에서 `SQLException`이 반환되서 예외가 던져지면 `translator.translate("save", sql, e)`를 통해 예외를 던진다.

이 `translate()`가 반환하는 예외는 런타임 예외이므로 서비스 계층에서 잡을 필요가 없다. 따라서 특정 구현 기술에 의존성이 생기지 않는다.

다음과 같이 앞서 작성했던 `MemberServiceTestV4`의 테스트 설정을 변경한다.

```java
@TestConfiguration
static class TestConfig {
    private final DataSource dataSource;

    public TestConfig(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Bean
    MemberRepository memberRepositoryV4() {
        return new MemberRepositoryV4_2(dataSource);
    }

    @Bean
    MemberServiceV4 memberServiceV4() {
        return new MemberServiceV4(memberRepositoryV4());
    }
}
```

이제 `MemberService`는 `MemberRepository` 인터페이스를 의존하므로 구현체를 쉽게 변경할 수 있다.

예외 발생 로그를 확인해보기 위해서 `MemberRepositoryV4_2`에 문법 오류가 나도록 `sql`을 아무렇게나 수정하고 테스트를 돌리면 다음과 같은 결과가 출력된다.

```
findById; bad SQL grammar [SELECT * FROM member WHERE member_idasd = ?]
org.springframework.jdbc.BadSqlGrammarException: findById; bad SQL grammar [SELECT * FROM member WHERE member_idasd = ?]
```

> [!summary] 정리
> 스프링이 예외를 추상화해준 덕분에, 서비스 계층은 특정 리포지토리의 구현 기술과 예외에 종속적이지 않게 되었다. 따라서 서비스 계층은 특정 구현 기술이 변경되어도 그대로 유지할 수 있게 되었다.
>
> 다시 DI를 제대로 활용할 수 있게 된 것이다.
>
> 추가로 서비스 계층에서 예외를 잡아서 복구해야 하는 경우, 예외가 스프링이 제공하는 데이터 접근 예외로 변경되어서 서비스 계층에 넘어오기 때문에 필요한 경우 예외를 잡아서 복구하면 된다.

---

References: 김영한의 스프링 DB 1편

Links to this page:
